version: "3.8"

services:
  nextjs-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-portfolio
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
